[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npx prisma generate --config prisma.config.mjs",
  "npx tsc",
  "node scripts/copy-prisma.js",
  "npx prisma migrate deploy"
]

[start]
cmd = "node dist/server.js"